#!/usr/bin/python3
import sys

def rsa(integer: int):
    for i in range(2, integer):
        if not integer % i:
            return i

def main():
    file_name = sys.argv[1]
    with open(file_name) as file:
        data = [int(integer) for integer in file.readlines()]
    for n in data:
        print(f"{n}={n//rsa(n)}*{rsa(n)}")
    

if __name__ == "__main__":
    main()